modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="mintchoco_delight.png"
authors="${mod_authors}"
description='''${mod_description}'''

# Forge 与 Minecraft
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# 农夫乐事为硬依赖
[[dependencies.${mod_id}]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.3.0,)"
    ordering="NONE"
    side="BOTH"

# 机械动力为软依赖：安装后启用搅拌/灌装/倒空等自动化配方，未安装则相关配方不加载
[[dependencies.${mod_id}]]
    modId="create"
    mandatory=false
    versionRange="[6.0,)"
    ordering="NONE"
    side="BOTH"
