modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="mintchoco_delight.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

# NeoForge 与 Minecraft
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Create 为硬依赖
[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.0,6.1.0)"
    ordering="NONE"
    side="BOTH"

# 农夫乐事为硬依赖
[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"

# Create Crafts & Additions 为软依赖：未安装时仅跳过「烘焙蛋糕底座」相关配方
[[dependencies.${mod_id}]]
    modId="createaddition"
    type="optional"
    versionRange="[1.7.0,)"
    ordering="NONE"
    side="BOTH"